### ISSUE TITLE
Resturant

### ISSUE THREAD

**Issue by vinodshidlani** [anupam42/PG-Miscellaneous#6]
In Resturant Birthday party, wedding anniversary and other conference purpose customers they reserve whole resturant then how they reserved resturant can have idea...

**Comment by moghribalakrishna** [comment]
Look little confusing, please explain it in better way and in the future add these defects to either DAPP or MAPP for future milestones.

**Comment by moghribalakrishna** [comment]
Got it. I think You meant how to handle reservations for more than one table., will log this feature in PDAPP, better you too follow that.
